# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Gatsby Publish

on:
  push:
    branches: [ master ]

jobs:
  Publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: yarn
      working-directory: ./web
    - run: git config --global user.email "kavimaluskam@gmail.com"
    - run: git config --global user.name "Alex Kam"
    - shell: bash
      working-directory: ./web
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: yarn deploy
